### ISSUE TITLE
Something config file wrong when running your sample.

### ISSUE THREAD

**Issue by linhuixiao** [segwayrobotics/segway_DRIVE_benchmark#1]
Hi, I just want to try your dataset by using VINS-mone, but something config wrong was happened. 
In https://drive.segwayrobotics.com/#/overview/index2, the rosbag .yaml shows maplab_ncamera.yaml, , Is this the Euroc Dataset yaml file in maplab? ( I havn't see some common name config file in maplab or your github /config or in rosbag info).
also the same, in https://github.com/segwayrobotics/segway_DRIVE_benchmark/tree/master/configs, the only two config file is respect to realsense. Does the sensor is use realsense? It havn't noted in the dataset web homepage.

**Comment by qinyusen** [comment]
Hi, Thank you for the question ,config is on the way.
You will find it on the web later.

Dataset web page will update in this week, we are preparing for release more data in the past weeks.

Thanks, I will close this issue when the update is ready.

**Comment by qinyusen** [comment]
Hi, Huixiao
Now the yaml file could be found in the part of Download on the page:
https://drive.segwayrobotics.com/#/dataset/index

or you can simply download it from: 
https://drive.segwayrobotics.com/dist/static/webpage/sample-dataset.yaml
