### ISSUE TITLE
Request for data sequence

### ISSUE THREAD

**Issue by DunFenTiao** [segwayrobotics/segway_DRIVE_benchmark#5]
I find there is no **2018-08-02 18-42-03 of B6 B1** sequence on dataset download website(https://drive.segwayrobotics.com/dataset/download), which sequence has figure and value of pose metrics on your paper.

Could i have this sequence for a more completed comparison?

**Comment by qinyusen** [comment]
some of data is refreshed.

**Comment by qinyusen** [comment]
https://lifelong-robotic-vision.github.io/dataset/scene

You can try this dataset with more sensors

**Comment by JzHuai0108** [comment]
I recall that 2018-08-02 18-42-03 of B6 B1 missed data from some sensor modality, therefore it was not uploaded to the download page. I don't have access to the aged data at the moment.
